version: '3.2'

services:

  web_worker:
    build:
      context: ""
      dockerfile: Dockerfile
    entrypoint: /opt/devspaces/entrypoint.sh
    command: tail -f /dev/null
    volumes:
    - type: bind
      source: ../../rails_activejob_example
      target: /data
    environment:
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_ENV: production
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: sidekiq_db
      DB_USER: sidekiq_usr
      DB_PASSWORD: sidekiq_pwd
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      SECRET_KEY_BASE: 6c274da024af575b12ffe358ac8381e85060a600d837d08c4bb380079c95f7675db69c30bc0ca96b63ed2b8c121f7311c716433ac21a278d302fafe19145c6b8
    ports:
    - 3000:3000
    networks:
    - web_worker_network
    container_name: web_worker

networks:
  web_worker_network:
